[features]
seeds = false
[programs.localnet]
soltwitter = "H3tP4URvzTw9iow9aPynthyzSwGGoZLbXt34LVbhDE66"
[programs.devnet]
soltwitter = "H3tP4URvzTw9iow9aPynthyzSwGGoZLbXt34LVbhDE66"
[programs.mainnet]
soltwitter = "H3tP4URvzTw9iow9aPynthyzSwGGoZLbXt34LVbhDE66"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/tripboi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
