[features]
seeds = false
[programs.localnet]
soltwitter = "H3tP4URvzTw9iow9aPynthyzSwGGoZLbXt34LVbhDE66"
[programs.devnet]
soltwitter = "H3tP4URvzTw9iow9aPynthyzSwGGoZLbXt34LVbhDE66"
[programs.mainnet]
soltwitter = "H3tP4URvzTw9iow9aPynthyzSwGGoZLbXt34LVbhDE66"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/tripboi/.config/solana/id.json"

[scripts]
copy-idl = "mkdir -p app/src/idl && cp target/idl/soltwitter.json app/src/idl/soltwitter.json"
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
